FROM node:8.6.0

LABEL description="dcr-netstats build"
LABEL version="1.0"
LABEL maintainer "holdstockjamie@gmail.com"

USER root
WORKDIR /root

COPY ./ /root/

RUN npm install -g grunt-cli pm2 && \
    npm install 

RUN grunt

CMD pm2 startOrRestart package.json --env=production
